### ISSUE TITLE
Framework API Response not visible

### ISSUE THREAD

**Issue by hpDeviOS** [FLEXTool/FLEX#676] opened 2023-08-24 10:57 UTC
### Discussed in https://github.com/FLEXTool/FLEX/discussions/612

<div type='discussions-op-text'>

<sup>Originally posted by **hpDeviOS** July 20, 2022</sup>
I am working on the iOS Framework and App, both have API calls.
The framework used in App.

So, whenever I use FLEX in App, whatever API calls under the framework its response receive successfully but is **NOT VISIBLE in flex**. (showing awaiting for response).

This issue only when API calls from Framework, no issue for API calls from App.

![IMG_9EA726D5BC05-1](https://user-images.githubusercontent.com/22273964/179837803-4c854661-e4fc-4acd-bbc4-d6883b04d0aa.jpeg)

Is there any configuration that needs to make in App or Framework?
or
anything else.</div>

**Comment by SuryakantRapido** [comment] 2023-08-28 08:43
is Anyone fixing issue ?

**Comment by bplattenburg** [comment] 2023-10-16 14:12
This appears to be a duplicate of https://github.com/FLEXTool/FLEX/issues/646

**Comment by NSExceptional** [comment] 2024-08-25 21:02
Closing as dupe of #646 for now

**Closed by NSExceptional** 2024-08-25 21:02 UTC
