### ISSUE TITLE
Network History open,but not date

### ISSUE THREAD

**Issue by XSFlyer** [FLEXTool/FLEX#478] opened 2020-10-26 07:09 UTC
I have opened Network History, but no data has been received

**Comment by NSExceptional** [comment] 2020-10-26 15:04
Are you trying to inspect WKWebView traffic?

**Comment by yaroslavYS** [comment] 2020-11-04 12:18
I'm too - observing 0 requests

![Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 14 18 05](https://user-images.githubusercontent.com/1153954/98110974-9b133b80-1ea8-11eb-9fe4-487e18e96bd2.png)
![Uploading Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 14.18.11.png…]()

**Comment by NSExceptional** [comment] 2020-11-04 17:05
@yaroslavYS Same question, are you trying to observe a web view?

**Comment by yaroslavYS** [comment] 2020-11-04 17:16
no - just executing any API server request
it was working in the past perfectly

now it's iOS 14. internally I'm using AFNetworking (latest - 4.0.1)

**Comment by NSExceptional** [comment] 2020-11-04 18:10
Oh boy, another AFNetworkint issue 😓

Thanks, I'll look into this.

**Comment by NSExceptional** [comment] 2020-11-04 18:31
@yaroslavYS I found an old example project for this sort of issue so I was able to look at it fast. Using iOS 14 and AFNetworking 4.0.1 I am unable to reproduce this issue.

If you can provide an example project for me, I can look at it

**Comment by yakupcaglan** [comment] 2020-11-13 06:59
same problem.

**Comment by NSExceptional** [comment] 2020-11-15 07:31
@yaroslavYS do you have a sample app you can share with me?

**Comment by yaroslavYS** [comment] 2020-11-18 12:10
unfortunately - I don't have open source project to show, it's my Enterprise NDA project

**Comment by yaroslavYS** [comment] 2020-11-18 12:11
it seems like other people also reporting this, can they show their projects?

**Comment by NSExceptional** [comment] 2020-11-18 15:42
Ask you can see no one else has a project to share either apparently 😅

**Comment by NSExceptional** [comment] 2020-12-17 07:50
Closing this in favor of a discussion since this is a common issue. Please direct further comments to #495.

**Closed by NSExceptional** 2020-12-17 07:50 UTC
Labels: awaiting response
