### ISSUE TITLE
Z-order bug after app popup causes total UI lock

### ISSUE THREAD

**Issue by badger200** [FLEXTool/FLEX#519] opened 2021-03-12 12:52 UTC
iOS 12.4
FLEXing 4.4.0

This bug is reproducible when I have the FLEX toolbar open, browse an element into its View Controller, then call a void Method in an app which downloads an image for 2-10 seconds, and then pops up a completion dialog with 2 button choices. If I close the FLEX window quickly while the image is downloading, everything is fine.

Otherwise, it seems like there some kind of z-order glitch happening, where the app’s pop up dialog is visible and appears active, but it’s actually not, and while FLEX toolbar is visible, it’s not responsive. So you end up with a completely non-responsive UI. Trying the 3 finger and status bar taps do nothing.

The app I happen to be using is ReShare Story by Eduardo from the App Store (you need an Instagram account but then just try downloading any video, that should take long enough to make the bug occur).

To rephrase this, it’s like FLEX needs to accommodate the scenario where the user taps a multithreaded command that won’t return until some time later, at which point it will pop up and command Focus, pulling the rug out from underneath FLEX which thinks it still has focus.

**Comment by NSExceptional** [comment] 2021-03-12 20:15
I think it has something to do with apps creating a UIWindow just to present a alert from anywhere without needing a reference to a specific view controller. Something similar happens in iCleaner Pro and it's been long on my todo list to fix 😓

Thanks for the report!

**Comment by NSExceptional** [comment] 2021-04-05 16:35
This app is not available in the US apparently :/ If you can send me the IPA I can debug it

**Comment by NSExceptional** [comment] 2021-04-05 17:58
Seems related to this issue: https://github.com/NSExceptional/FLEXing/issues/13

But I fixed that issue I think, if you look at the history at the bottom. I would really like that IPA though so I can see what's happening!

**Comment by badger200** [comment] 2021-04-07 17:36
Hi, thanks for this brilliant follow up investigation 👍🏼
I am emailing you privately, will send in approximately 3 minutes.

**Comment by badger200** [comment] 2021-06-06 20:42
Did you ever have a chance to explore that .IPA I emailed you? I don't check my email very often so let me know if I've missed it. 

I know I sent you an absolutely massive email with a dozen bullet points and that's probably super overwhelming lol, this happens to me all the time😆

**Comment by NSExceptional** [comment] 2021-06-07 16:10
I have not 😅 I'm sorry

I do still have your email, it's pinned to my inbox. It's on my todo list

**Comment by NSExceptional** [comment] 2022-04-22 17:49
So I tried installing this today, but just my luck, seems all the sideloading tools out there are broken…

**Comment by NSExceptional** [comment] 2022-10-01 22:29
Closing this since your last reply was over a year ago, lmk if you want to help me reproduce this sometime and I can reopen it

**Closed by NSExceptional** 2022-10-01 22:29 UTC
Labels: bug, awaiting response
