### ISSUE TITLE
Awaiting Response

### ISSUE THREAD

**Issue by topik96** [FLEXTool/FLEX#663] opened 2023-04-05 09:29 UTC
### Environment
- Platform+version: **iOS 16** 
- FLEX version: **5.22.10** 

### Bug Report
Status is **Awaiting Response**
<img width="360" alt="Screen Shot 2023-04-05 at 16 28 15" src="https://user-images.githubusercontent.com/12253475/230040525-e902b070-8184-406b-8ba4-c820f576cab7.png">

**Comment by brianplattenburg-delta** [comment] 2023-05-04 12:33
Potentially a duplicate of https://github.com/FLEXTool/FLEX/issues/646?

**Comment by topik96** [comment] 2023-08-03 03:20
Ah, I will close this ticket @brianplattenburg-delta . Thanks

**Closed** 2023-08-03 03:20 UTC
Labels: bug
