### ISSUE TITLE
Remove Non-Inclusive Terms

### ISSUE THREAD

**Issue by tinder-owenthomas** [FLEXTool/FLEX#509] opened 2021-02-17 23:40 UTC
### Issue Info

FLEX currently has several references to non-inclusive terms.

### Issue Description and Steps

Can we please get an updated version of the SDK which removes all non-inclusive language? We are focusing on removing such language from our company which extends to all third-party code we choose to use.

Specifically terms such as [whitelist](https://github.com/FLEXTool/FLEX/search?q=whitelist) (also [here](https://github.com/FLEXTool/FLEX/search?q=whitelistedDefaults), [here](https://github.com/FLEXTool/FLEX/search?q=whitelisting), and [here](https://github.com/FLEXTool/FLEX/search?q=%22whitelisted+keys%22)), [blacklist](https://github.com/FLEXTool/FLEX/search?q=blacklist) (also [here](https://github.com/FLEXTool/FLEX/search?q=networkRequestHostBlacklist), [here](https://github.com/FLEXTool/FLEX/search?q=synchronizeBlacklist), and [here](https://github.com/FLEXTool/FLEX/search?q=clearBlacklistedTransactions)), [master](https://github.com/FLEXTool/FLEX/search?q=master), slave, etc. Would love this to cover actual code of course, but also, comments, branch names, repo descriptions on dependency management central repositories, licensing agreements, etc.

**Comment by badger200** [comment] 2021-03-02 17:02
Lol I can’t tell if this is sarcastic or not. As if someone’s going to expend the effort for such a petty change - and then do it for all sublicenses to which they’re not even the author just to create some bastardized version (oops was that a “Non-Inclusive” term?) for you for some arbitrary reason.

Terms like master and slave inherently have nothing to do with inclusivity, they’re used in other fields of engineering the same way, like the master cylinder on your vehicle’s brake system.

Your intentions are honorable but would be a thousand times better spent in an area ACTUALLY affecting someone. There is no human slavery happening in software, nor in your car’s brake system. 

This feels like a corporate-mandated performance/phony social justice for the sake of feeling like you’re helping the cause, while actually diminishing it in a real sense. I certainly just lost some respect for the inclusivity movement. Unless this was sarcasm, but the fact you’re a developer at a huge app makes me think it’s a sincere request..

**Comment by lechium** [comment] 2021-03-03 18:53
whats next? renaming a masters degree or mastercard? this is embarassing.

**Comment by tinder-owenthomas** [comment] 2021-03-04 20:27
I understand where you are coming from @badger200. As a very privileged white, abled, American, male, etc. I too used to feel that efforts like this were not important - because they didn't impact me so I didn't see or understand them. But over the past several years I've come to realize just how important they are to others, and therefore to our society more broadly, myself included. I have met frequently with people for whom the use of non-inclusive terminology is hurtful, demeaning, and marginalizing, and came to understand how truly important this is. I'd urge you to go out and talk to some marginalized groups at your workplace, friend group, the broader iOS engineering community, etc. and hear directly from them how a culture of exclusion has impacted them in ways we may never fully understand. Just because it doesn't impact you and me directly to the same extent, doesn't mean it is unimportant.

Separately, this is an important initiative for my company as we believe in fully embracing diversity, equity, and inclusion. Terms like master, slave, whitelist, blacklist, etc. in use in technology are in fact directly derived from slavery and/or other historical and societal forms of oppression and discrimination - even though it may not seem like it, and even though these terms are generally not used consciously in that way by engineers today. Unfortunately, the continued use of these terms - even unintentionally - by respected companies and individuals is highly offensive to groups of people who are already marginalized in so many other ways and continues and reinforces the culture of oppression that we have today. You and I may not see it because we likely benefit from this culture, but it comes at a great cost to others.

On a more personal level, these terms are triggering for me now that I have learned more about their impact on individuals and society in general - not to mention my direct co-workers whom I greatly respect, and the members who use our company's technology on a daily basis. Refusing to make these types of simple changes now that we know better is a direct slap in the face to all these people, which I find unacceptable.

For all the above reasons we are actively working to correct past mistakes by removing non-inclusive terminology, and we are far from alone in this effort. Many other large reputable software engineering groups are doing the same thing in an attempt to level the playing field for all people: [Apple](https://appleinsider.com/articles/20/07/17/apple-to-remove-replace-non-inclusive-language-in-code-base), [Github](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/), [IBM & Microsoft](https://www.zdnet.com/article/ibm-microsoft-staff-rally-to-remove-racially-insensitive-language-from-products/), [Twitter & JPMorgan](https://www.cnn.com/2020/07/03/tech/twitter-jpmorgan-slave-master-coding/index.html), [The Linux Kernel Team](https://itsfoss.com/linux-kernel-inclusive-code), [MySQL](https://www.zdnet.com/article/mysql-drops-master-slave-and-blacklist-whitelist-terminology/), and hundreds of others.

I hope through discussions like this you can come to appreciate the importance of this effort, even if only for others, and help be part of the change that is essential to move our society - and software engineering much more specifically - in the right direction.

**Comment by NSExceptional** [comment] 2021-03-26 20:19
Apologies for my delayed response, @tinder-owenthomas! It's been a busy month for me; I've only been responding to PRs or issues I could either merge or close immediately.

Rest assured, I will do my best to implement the requested changes when I can find the time. I see nothing wrong with renaming things in the codebase to be more clear and inclusive, especially since none of it would be an API-breaking change.

**Comment by NSExceptional** [comment] 2021-03-29 23:09
Fixed in 4.4.1 🎉

**Closed by NSExceptional** 2021-03-29 23:09 UTC
Labels: enhancement

**Comment by badger200** [comment] 2021-04-17 12:54
@tinder-owenthomas I read your entire comment and may yet view some of the impressive links you provided. I respect your efforts, and the cause, but I still feel like this is social justice taken to an absurd level.

I’m an American with German heritage. I suppose I could take offense at terms like “grammar nazi” and others, but none of those things have ever bothered me in any personal way whatsoever because it bears no tangible relationship to me or anyone even in my extended family, and even if it did, I would still know that the person is obviously using it as merely common slang and not some specific vendetta against people of German descent. 

Nevertheless I will keep your arguments in mind going forward, and thanks for taking the time to offer some insight.

**Comment by NSExceptional** [comment] 2021-04-21 17:00
@tinder-owenthomas This is probably not the right place for me to ask, but I'm not sure how else to contact you so I'm just gonna go for it: is your company hiring more iOS positions? It makes me happy to know Tinder uses something I work on, and I would love to work at Tinder, too.

**Comment by tinder-owenthomas** [comment] 2021-04-21 17:27
@NSExceptional we are pretty much always hiring for good talent. Connect with me on LinkedIn. Happy to chat about it!

https://www.linkedin.com/in/owenhthomas

**Comment by SoCuul** [comment] 2025-05-05 06:31
> [@tinder-owenthomas](https://github.com/tinder-owenthomas) This is probably not the right place for me to ask, but I'm not sure how else to contact you so I'm just gonna go for it: is your company hiring more iOS positions? It makes me happy to know Tinder uses something I work on, and I would love to work at Tinder, too.

congrats on this working out haha
