### ISSUE TITLE
Exception: [NSMethodSignature signatureWithObjCTypes:]: type signature is NULL.

### ISSUE THREAD

**Issue by Ram4096** [FLEXTool/FLEX#412] opened 2020-04-11 01:04 UTC
I cannot often open certain instances, because the app crashes with this exception:

```Exception type: NSInvalidArgumentException
Reason: +[NSMethodSignature signatureWithObjCTypes:]: type signature is NULL.
```
We already discussed about this problem, but this didn't happen in old libFLEX versions. Isn't it possible to restore the old behavior?

Note that I've also noticed that sometimes, when the returned value of a method is ```void```, I see ```?```.

**Comment by NSExceptional** [comment] 2020-04-11 01:06
Can you use the debugger and pinpoint the case that is causing the crash? Ie which method / class?

**Comment by NSExceptional** [comment] 2020-04-11 01:06
The `?` bug was fixed in 4.1

**Comment by Ram4096** [comment] 2020-04-11 01:09
> Can you use the debugger and pinpoint the case that is causing the crash? Ie which method / class?

I would love to help you using a debugger, but I'm unable to do it. I never used a debugger and I'm not really sure it's possible with Windows (I have not MacOS)

**Comment by NSExceptional** [comment] 2020-04-11 01:13
What are you doing in which app that causes the crash?

**Comment by Ram4096** [comment] 2020-04-11 01:59
> What are you doing in which app that causes the crash?

I've finally discovered the reason. Nothing related to FLEX fortunately. I created a sort of anti-tweak detection and FLEX crashed because it was unable to find the methods of a class/instance implemented in a tweak.

Thanks always to be so available to fix bugs.

**Comment by NSExceptional** [comment] 2020-04-11 17:31
Still, FLEX should never crash, even if you think it's your code letting flex crash. If you can provide a crash log or a debugger screenshot that would be very helpful

**Comment by Ram4096** [comment] 2020-04-11 19:04
> Still, FLEX should never crash, even if you think it's your code letting flex crash. If you can provide a crash log or a debugger screenshot that would be very helpful

I've privately send the code that makes FLEX to crash.

**Comment by NSExceptional** [comment] 2020-04-15 05:13
So the issue is that `class_getClassMethod` and `class_getClassMethod` are being hooked to return `nil` for some classes. FLEX needs to account for this. Thanks!

**Comment by NSExceptional** [comment] 2020-10-22 19:00
So in your specific instance, you aren't hooking `respondsToSelector:` as well, and you should be. For example, if your hook looks like this:

```logos
%hookf (id, class_getInstanceMethod, Class cls, SEL sel) {
    if (cls == [SomeClass class] && sel == @selector(selToHide:))
        return nil;
    return %orig;
}
```

You also need to hook `-[SomeClass respondsToSelector:]` as well as `+[SomeClass instancesRespondToSelector:]` to return `NO` for that particular selector. The reason FLEX is crashing is because it first calls this method, and after that, `class_get*Method` should NOT return `nil`.

Closing as won't fix

**Closed by NSExceptional** 2020-10-22 19:00 UTC
Labels: bug
